// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestServer.Models;

namespace RestServer.Migrations
{
    [DbContext(typeof(RestServerContext))]
    [Migration("20210726232507_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("RestServer.Models.Drawing", b =>
                {
                    b.Property<int>("DrawingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Kicker")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Num1")
                        .HasColumnType("int");

                    b.Property<int>("Num2")
                        .HasColumnType("int");

                    b.Property<int>("Num3")
                        .HasColumnType("int");

                    b.Property<int>("Num4")
                        .HasColumnType("int");

                    b.Property<int>("Num5")
                        .HasColumnType("int");

                    b.HasKey("DrawingId");

                    b.ToTable("Drawings");

                    b.HasData(
                        new
                        {
                            DrawingId = 1,
                            Date = "1/10/21",
                            Kicker = 7,
                            Name = "Power Ball",
                            Num1 = 1,
                            Num2 = 5,
                            Num3 = 17,
                            Num4 = 22,
                            Num5 = 45
                        },
                        new
                        {
                            DrawingId = 2,
                            Date = "1/10/21",
                            Kicker = 1,
                            Name = "Power Ball",
                            Num1 = 7,
                            Num2 = 17,
                            Num3 = 48,
                            Num4 = 53,
                            Num5 = 56
                        },
                        new
                        {
                            DrawingId = 3,
                            Date = "1/10/21",
                            Kicker = 6,
                            Name = "Power Ball",
                            Num1 = 2,
                            Num2 = 35,
                            Num3 = 39,
                            Num4 = 47,
                            Num5 = 48
                        },
                        new
                        {
                            DrawingId = 4,
                            Date = "1/10/21",
                            Kicker = 13,
                            Name = "Power Ball",
                            Num1 = 32,
                            Num2 = 35,
                            Num3 = 38,
                            Num4 = 51,
                            Num5 = 52
                        },
                        new
                        {
                            DrawingId = 5,
                            Date = "1/10/21",
                            Kicker = 3,
                            Name = "Power Ball",
                            Num1 = 5,
                            Num2 = 8,
                            Num3 = 13,
                            Num4 = 34,
                            Num5 = 45
                        },
                        new
                        {
                            DrawingId = 6,
                            Date = "1/10/21",
                            Kicker = 16,
                            Name = "Power Ball",
                            Num1 = 6,
                            Num2 = 30,
                            Num3 = 44,
                            Num4 = 52,
                            Num5 = 58
                        },
                        new
                        {
                            DrawingId = 7,
                            Date = "1/10/21",
                            Kicker = 21,
                            Name = "Power Ball",
                            Num1 = 2,
                            Num2 = 15,
                            Num3 = 21,
                            Num4 = 35,
                            Num5 = 53
                        },
                        new
                        {
                            DrawingId = 8,
                            Date = "1/10/21",
                            Kicker = 18,
                            Name = "Power Ball",
                            Num1 = 7,
                            Num2 = 13,
                            Num3 = 23,
                            Num4 = 25,
                            Num5 = 33
                        },
                        new
                        {
                            DrawingId = 9,
                            Date = "1/10/21",
                            Kicker = 11,
                            Name = "Power Ball",
                            Num1 = 14,
                            Num2 = 15,
                            Num3 = 18,
                            Num4 = 34,
                            Num5 = 65
                        },
                        new
                        {
                            DrawingId = 10,
                            Date = "1/10/21",
                            Kicker = 11,
                            Name = "Power Ball",
                            Num1 = 21,
                            Num2 = 44,
                            Num3 = 50,
                            Num4 = 59,
                            Num5 = 66
                        },
                        new
                        {
                            DrawingId = 11,
                            Date = "1/10/21",
                            Kicker = 9,
                            Name = "Power Ball",
                            Num1 = 13,
                            Num2 = 23,
                            Num3 = 39,
                            Num4 = 41,
                            Num5 = 66
                        },
                        new
                        {
                            DrawingId = 12,
                            Date = "1/10/21",
                            Kicker = 15,
                            Name = "Power Ball",
                            Num1 = 8,
                            Num2 = 40,
                            Num3 = 41,
                            Num4 = 51,
                            Num5 = 53
                        },
                        new
                        {
                            DrawingId = 13,
                            Date = "1/10/21",
                            Kicker = 27,
                            Name = "Power Ball",
                            Num1 = 9,
                            Num2 = 21,
                            Num3 = 41,
                            Num4 = 49,
                            Num5 = 56
                        },
                        new
                        {
                            DrawingId = 14,
                            Date = "1/10/21",
                            Kicker = 17,
                            Name = "Power Ball",
                            Num1 = 2,
                            Num2 = 40,
                            Num3 = 51,
                            Num4 = 64,
                            Num5 = 67
                        },
                        new
                        {
                            DrawingId = 15,
                            Date = "1/10/21",
                            Kicker = 20,
                            Name = "Power Ball",
                            Num1 = 16,
                            Num2 = 32,
                            Num3 = 48,
                            Num4 = 63,
                            Num5 = 69
                        },
                        new
                        {
                            DrawingId = 16,
                            Date = "1/10/21",
                            Kicker = 7,
                            Name = "Power Ball",
                            Num1 = 3,
                            Num2 = 16,
                            Num3 = 22,
                            Num4 = 34,
                            Num5 = 48
                        },
                        new
                        {
                            DrawingId = 17,
                            Date = "1/10/21",
                            Kicker = 16,
                            Name = "Power Ball",
                            Num1 = 30,
                            Num2 = 39,
                            Num3 = 57,
                            Num4 = 58,
                            Num5 = 60
                        },
                        new
                        {
                            DrawingId = 18,
                            Date = "1/10/21",
                            Kicker = 23,
                            Name = "Power Ball",
                            Num1 = 2,
                            Num2 = 20,
                            Num3 = 27,
                            Num4 = 45,
                            Num5 = 57
                        },
                        new
                        {
                            DrawingId = 19,
                            Date = "1/10/21",
                            Kicker = 7,
                            Name = "Power Ball",
                            Num1 = 24,
                            Num2 = 32,
                            Num3 = 36,
                            Num4 = 38,
                            Num5 = 60
                        },
                        new
                        {
                            DrawingId = 20,
                            Date = "1/10/21",
                            Kicker = 7,
                            Name = "Power Ball",
                            Num1 = 15,
                            Num2 = 32,
                            Num3 = 41,
                            Num4 = 60,
                            Num5 = 61
                        },
                        new
                        {
                            DrawingId = 21,
                            Date = "1/10/21",
                            Kicker = 23,
                            Name = "Power Ball",
                            Num1 = 13,
                            Num2 = 14,
                            Num3 = 18,
                            Num4 = 34,
                            Num5 = 65
                        },
                        new
                        {
                            DrawingId = 22,
                            Date = "1/10/21",
                            Kicker = 6,
                            Name = "Power Ball",
                            Num1 = 8,
                            Num2 = 23,
                            Num3 = 35,
                            Num4 = 59,
                            Num5 = 65
                        },
                        new
                        {
                            DrawingId = 23,
                            Date = "1/10/21",
                            Kicker = 9,
                            Name = "Power Ball",
                            Num1 = 5,
                            Num2 = 13,
                            Num3 = 35,
                            Num4 = 44,
                            Num5 = 56
                        },
                        new
                        {
                            DrawingId = 24,
                            Date = "1/10/21",
                            Kicker = 3,
                            Name = "Power Ball",
                            Num1 = 2,
                            Num2 = 33,
                            Num3 = 34,
                            Num4 = 60,
                            Num5 = 61
                        },
                        new
                        {
                            DrawingId = 25,
                            Date = "1/10/21",
                            Kicker = 23,
                            Name = "Power Ball",
                            Num1 = 5,
                            Num2 = 8,
                            Num3 = 19,
                            Num4 = 21,
                            Num5 = 24
                        },
                        new
                        {
                            DrawingId = 26,
                            Date = "1/10/21",
                            Kicker = 18,
                            Name = "Power Ball",
                            Num1 = 14,
                            Num2 = 47,
                            Num3 = 51,
                            Num4 = 56,
                            Num5 = 69
                        },
                        new
                        {
                            DrawingId = 27,
                            Date = "1/10/21",
                            Kicker = 9,
                            Name = "Power Ball",
                            Num1 = 9,
                            Num2 = 20,
                            Num3 = 29,
                            Num4 = 45,
                            Num5 = 47
                        },
                        new
                        {
                            DrawingId = 28,
                            Date = "1/10/21",
                            Kicker = 14,
                            Name = "Power Ball",
                            Num1 = 1,
                            Num2 = 8,
                            Num3 = 44,
                            Num4 = 53,
                            Num5 = 67
                        },
                        new
                        {
                            DrawingId = 29,
                            Date = "1/10/21",
                            Kicker = 10,
                            Name = "Power Ball",
                            Num1 = 4,
                            Num2 = 20,
                            Num3 = 31,
                            Num4 = 33,
                            Num5 = 53
                        },
                        new
                        {
                            DrawingId = 30,
                            Date = "1/10/21",
                            Kicker = 19,
                            Name = "Power Ball",
                            Num1 = 10,
                            Num2 = 24,
                            Num3 = 26,
                            Num4 = 51,
                            Num5 = 68
                        },
                        new
                        {
                            DrawingId = 31,
                            Date = "1/10/21",
                            Kicker = 24,
                            Name = "Power Ball",
                            Num1 = 16,
                            Num2 = 30,
                            Num3 = 35,
                            Num4 = 39,
                            Num5 = 58
                        },
                        new
                        {
                            DrawingId = 32,
                            Date = "1/10/21",
                            Kicker = 19,
                            Name = "Power Ball",
                            Num1 = 1,
                            Num2 = 5,
                            Num3 = 23,
                            Num4 = 24,
                            Num5 = 62
                        },
                        new
                        {
                            DrawingId = 33,
                            Date = "1/10/21",
                            Kicker = 1,
                            Name = "Power Ball",
                            Num1 = 6,
                            Num2 = 8,
                            Num3 = 22,
                            Num4 = 39,
                            Num5 = 40
                        },
                        new
                        {
                            DrawingId = 34,
                            Date = "1/10/21",
                            Kicker = 3,
                            Name = "Power Ball",
                            Num1 = 7,
                            Num2 = 19,
                            Num3 = 23,
                            Num4 = 54,
                            Num5 = 60
                        },
                        new
                        {
                            DrawingId = 35,
                            Date = "1/10/21",
                            Kicker = 15,
                            Name = "Power Ball",
                            Num1 = 5,
                            Num2 = 39,
                            Num3 = 53,
                            Num4 = 54,
                            Num5 = 63
                        },
                        new
                        {
                            DrawingId = 36,
                            Date = "1/10/21",
                            Kicker = 21,
                            Name = "Power Ball",
                            Num1 = 7,
                            Num2 = 20,
                            Num3 = 40,
                            Num4 = 45,
                            Num5 = 69
                        },
                        new
                        {
                            DrawingId = 37,
                            Date = "1/10/21",
                            Kicker = 24,
                            Name = "Power Ball",
                            Num1 = 13,
                            Num2 = 16,
                            Num3 = 20,
                            Num4 = 35,
                            Num5 = 50
                        },
                        new
                        {
                            DrawingId = 38,
                            Date = "1/10/21",
                            Kicker = 19,
                            Name = "Power Ball",
                            Num1 = 19,
                            Num2 = 23,
                            Num3 = 39,
                            Num4 = 59,
                            Num5 = 68
                        },
                        new
                        {
                            DrawingId = 39,
                            Date = "1/10/21",
                            Kicker = 14,
                            Name = "Power Ball",
                            Num1 = 2,
                            Num2 = 7,
                            Num3 = 15,
                            Num4 = 37,
                            Num5 = 57
                        },
                        new
                        {
                            DrawingId = 40,
                            Date = "1/10/21",
                            Kicker = 24,
                            Name = "Power Ball",
                            Num1 = 2,
                            Num2 = 34,
                            Num3 = 37,
                            Num4 = 46,
                            Num5 = 65
                        },
                        new
                        {
                            DrawingId = 41,
                            Date = "1/10/21",
                            Kicker = 6,
                            Name = "Power Ball",
                            Num1 = 18,
                            Num2 = 27,
                            Num3 = 32,
                            Num4 = 39,
                            Num5 = 67
                        },
                        new
                        {
                            DrawingId = 42,
                            Date = "1/10/21",
                            Kicker = 8,
                            Name = "Power Ball",
                            Num1 = 15,
                            Num2 = 40,
                            Num3 = 45,
                            Num4 = 57,
                            Num5 = 64
                        },
                        new
                        {
                            DrawingId = 43,
                            Date = "1/10/21",
                            Kicker = 28,
                            Name = "Power Ball",
                            Num1 = 12,
                            Num2 = 15,
                            Num3 = 34,
                            Num4 = 37,
                            Num5 = 49
                        },
                        new
                        {
                            DrawingId = 44,
                            Date = "1/10/21",
                            Kicker = 10,
                            Name = "Power Ball",
                            Num1 = 8,
                            Num2 = 12,
                            Num3 = 36,
                            Num4 = 46,
                            Num5 = 49
                        },
                        new
                        {
                            DrawingId = 45,
                            Date = "1/10/21",
                            Kicker = 14,
                            Name = "Power Ball",
                            Num1 = 1,
                            Num2 = 24,
                            Num3 = 39,
                            Num4 = 53,
                            Num5 = 54
                        },
                        new
                        {
                            DrawingId = 46,
                            Date = "1/10/21",
                            Kicker = 8,
                            Name = "Power Ball",
                            Num1 = 5,
                            Num2 = 31,
                            Num3 = 33,
                            Num4 = 51,
                            Num5 = 52
                        },
                        new
                        {
                            DrawingId = 47,
                            Date = "1/10/21",
                            Kicker = 22,
                            Name = "Power Ball",
                            Num1 = 26,
                            Num2 = 30,
                            Num3 = 38,
                            Num4 = 57,
                            Num5 = 59
                        },
                        new
                        {
                            DrawingId = 48,
                            Date = "1/10/21",
                            Kicker = 26,
                            Name = "Power Ball",
                            Num1 = 7,
                            Num2 = 17,
                            Num3 = 19,
                            Num4 = 44,
                            Num5 = 67
                        },
                        new
                        {
                            DrawingId = 49,
                            Date = "1/10/21",
                            Kicker = 17,
                            Name = "Power Ball",
                            Num1 = 2,
                            Num2 = 4,
                            Num3 = 10,
                            Num4 = 47,
                            Num5 = 51
                        },
                        new
                        {
                            DrawingId = 50,
                            Date = "1/10/21",
                            Kicker = 2,
                            Name = "Power Ball",
                            Num1 = 8,
                            Num2 = 10,
                            Num3 = 18,
                            Num4 = 33,
                            Num5 = 46
                        },
                        new
                        {
                            DrawingId = 51,
                            Date = "1/10/21",
                            Kicker = 13,
                            Name = "Power Ball",
                            Num1 = 6,
                            Num2 = 22,
                            Num3 = 60,
                            Num4 = 62,
                            Num5 = 66
                        },
                        new
                        {
                            DrawingId = 52,
                            Date = "1/10/21",
                            Kicker = 9,
                            Name = "Power Ball",
                            Num1 = 24,
                            Num2 = 41,
                            Num3 = 47,
                            Num4 = 57,
                            Num5 = 66
                        },
                        new
                        {
                            DrawingId = 53,
                            Date = "1/10/21",
                            Kicker = 4,
                            Name = "Power Ball",
                            Num1 = 24,
                            Num2 = 31,
                            Num3 = 42,
                            Num4 = 52,
                            Num5 = 68
                        },
                        new
                        {
                            DrawingId = 54,
                            Date = "1/10/21",
                            Kicker = 16,
                            Name = "Power Ball",
                            Num1 = 25,
                            Num2 = 36,
                            Num3 = 55,
                            Num4 = 60,
                            Num5 = 61
                        },
                        new
                        {
                            DrawingId = 55,
                            Date = "1/10/21",
                            Kicker = 22,
                            Name = "Power Ball",
                            Num1 = 3,
                            Num2 = 4,
                            Num3 = 22,
                            Num4 = 33,
                            Num5 = 55
                        },
                        new
                        {
                            DrawingId = 56,
                            Date = "1/10/21",
                            Kicker = 21,
                            Name = "Power Ball",
                            Num1 = 10,
                            Num2 = 23,
                            Num3 = 41,
                            Num4 = 53,
                            Num5 = 66
                        },
                        new
                        {
                            DrawingId = 57,
                            Date = "1/10/21",
                            Kicker = 7,
                            Name = "Power Ball",
                            Num1 = 2,
                            Num2 = 43,
                            Num3 = 44,
                            Num4 = 54,
                            Num5 = 58
                        },
                        new
                        {
                            DrawingId = 58,
                            Date = "1/10/21",
                            Kicker = 4,
                            Name = "Power Ball",
                            Num1 = 2,
                            Num2 = 11,
                            Num3 = 45,
                            Num4 = 49,
                            Num5 = 61
                        },
                        new
                        {
                            DrawingId = 59,
                            Date = "1/10/21",
                            Kicker = 2,
                            Name = "Power Ball",
                            Num1 = 8,
                            Num2 = 28,
                            Num3 = 47,
                            Num4 = 50,
                            Num5 = 60
                        },
                        new
                        {
                            DrawingId = 60,
                            Date = "1/10/21",
                            Kicker = 25,
                            Name = "Power Ball",
                            Num1 = 13,
                            Num2 = 27,
                            Num3 = 48,
                            Num4 = 49,
                            Num5 = 64
                        },
                        new
                        {
                            DrawingId = 61,
                            Date = "1/10/21",
                            Kicker = 15,
                            Name = "Power Ball",
                            Num1 = 1,
                            Num2 = 5,
                            Num3 = 17,
                            Num4 = 22,
                            Num5 = 45
                        },
                        new
                        {
                            DrawingId = 62,
                            Date = "1/10/21",
                            Kicker = 26,
                            Name = "Power Ball",
                            Num1 = 7,
                            Num2 = 17,
                            Num3 = 48,
                            Num4 = 53,
                            Num5 = 56
                        },
                        new
                        {
                            DrawingId = 63,
                            Date = "1/10/21",
                            Kicker = 12,
                            Name = "Power Ball",
                            Num1 = 2,
                            Num2 = 35,
                            Num3 = 39,
                            Num4 = 47,
                            Num5 = 48
                        },
                        new
                        {
                            DrawingId = 64,
                            Date = "1/10/21",
                            Kicker = 24,
                            Name = "Power Ball",
                            Num1 = 32,
                            Num2 = 35,
                            Num3 = 38,
                            Num4 = 51,
                            Num5 = 52
                        },
                        new
                        {
                            DrawingId = 65,
                            Date = "1/10/21",
                            Kicker = 26,
                            Name = "Power Ball",
                            Num1 = 5,
                            Num2 = 8,
                            Num3 = 13,
                            Num4 = 34,
                            Num5 = 45
                        },
                        new
                        {
                            DrawingId = 66,
                            Date = "1/10/21",
                            Kicker = 21,
                            Name = "Power Ball",
                            Num1 = 6,
                            Num2 = 30,
                            Num3 = 44,
                            Num4 = 52,
                            Num5 = 58
                        },
                        new
                        {
                            DrawingId = 67,
                            Date = "1/10/21",
                            Kicker = 2,
                            Name = "Power Ball",
                            Num1 = 2,
                            Num2 = 15,
                            Num3 = 21,
                            Num4 = 35,
                            Num5 = 53
                        },
                        new
                        {
                            DrawingId = 68,
                            Date = "1/10/21",
                            Kicker = 19,
                            Name = "Power Ball",
                            Num1 = 7,
                            Num2 = 13,
                            Num3 = 23,
                            Num4 = 25,
                            Num5 = 33
                        },
                        new
                        {
                            DrawingId = 69,
                            Date = "1/10/21",
                            Kicker = 16,
                            Name = "Power Ball",
                            Num1 = 14,
                            Num2 = 15,
                            Num3 = 18,
                            Num4 = 34,
                            Num5 = 65
                        },
                        new
                        {
                            DrawingId = 70,
                            Date = "1/10/21",
                            Kicker = 23,
                            Name = "Power Ball",
                            Num1 = 21,
                            Num2 = 44,
                            Num3 = 50,
                            Num4 = 59,
                            Num5 = 66
                        },
                        new
                        {
                            DrawingId = 71,
                            Date = "1/10/21",
                            Kicker = 9,
                            Name = "Power Ball",
                            Num1 = 13,
                            Num2 = 23,
                            Num3 = 39,
                            Num4 = 41,
                            Num5 = 66
                        },
                        new
                        {
                            DrawingId = 72,
                            Date = "1/10/21",
                            Kicker = 4,
                            Name = "Power Ball",
                            Num1 = 8,
                            Num2 = 40,
                            Num3 = 41,
                            Num4 = 51,
                            Num5 = 53
                        },
                        new
                        {
                            DrawingId = 73,
                            Date = "1/10/21",
                            Kicker = 28,
                            Name = "Power Ball",
                            Num1 = 9,
                            Num2 = 21,
                            Num3 = 41,
                            Num4 = 49,
                            Num5 = 56
                        },
                        new
                        {
                            DrawingId = 74,
                            Date = "1/10/21",
                            Kicker = 22,
                            Name = "Power Ball",
                            Num1 = 2,
                            Num2 = 40,
                            Num3 = 51,
                            Num4 = 64,
                            Num5 = 67
                        },
                        new
                        {
                            DrawingId = 75,
                            Date = "1/10/21",
                            Kicker = 28,
                            Name = "Power Ball",
                            Num1 = 16,
                            Num2 = 32,
                            Num3 = 48,
                            Num4 = 63,
                            Num5 = 69
                        },
                        new
                        {
                            DrawingId = 76,
                            Date = "1/10/21",
                            Kicker = 14,
                            Name = "Power Ball",
                            Num1 = 3,
                            Num2 = 16,
                            Num3 = 22,
                            Num4 = 34,
                            Num5 = 48
                        },
                        new
                        {
                            DrawingId = 77,
                            Date = "1/10/21",
                            Kicker = 15,
                            Name = "Power Ball",
                            Num1 = 30,
                            Num2 = 39,
                            Num3 = 57,
                            Num4 = 58,
                            Num5 = 60
                        },
                        new
                        {
                            DrawingId = 78,
                            Date = "1/10/21",
                            Kicker = 14,
                            Name = "Power Ball",
                            Num1 = 2,
                            Num2 = 20,
                            Num3 = 27,
                            Num4 = 45,
                            Num5 = 57
                        },
                        new
                        {
                            DrawingId = 79,
                            Date = "1/10/21",
                            Kicker = 1,
                            Name = "Power Ball",
                            Num1 = 24,
                            Num2 = 32,
                            Num3 = 36,
                            Num4 = 38,
                            Num5 = 60
                        },
                        new
                        {
                            DrawingId = 80,
                            Date = "1/10/21",
                            Kicker = 13,
                            Name = "Power Ball",
                            Num1 = 15,
                            Num2 = 32,
                            Num3 = 41,
                            Num4 = 60,
                            Num5 = 61
                        },
                        new
                        {
                            DrawingId = 81,
                            Date = "1/10/21",
                            Kicker = 22,
                            Name = "Power Ball",
                            Num1 = 13,
                            Num2 = 14,
                            Num3 = 18,
                            Num4 = 34,
                            Num5 = 65
                        },
                        new
                        {
                            DrawingId = 82,
                            Date = "1/10/21",
                            Kicker = 9,
                            Name = "Power Ball",
                            Num1 = 8,
                            Num2 = 23,
                            Num3 = 35,
                            Num4 = 59,
                            Num5 = 65
                        },
                        new
                        {
                            DrawingId = 83,
                            Date = "1/10/21",
                            Kicker = 15,
                            Name = "Power Ball",
                            Num1 = 5,
                            Num2 = 13,
                            Num3 = 35,
                            Num4 = 44,
                            Num5 = 56
                        },
                        new
                        {
                            DrawingId = 84,
                            Date = "1/10/21",
                            Kicker = 4,
                            Name = "Power Ball",
                            Num1 = 2,
                            Num2 = 33,
                            Num3 = 34,
                            Num4 = 60,
                            Num5 = 61
                        },
                        new
                        {
                            DrawingId = 85,
                            Date = "1/10/21",
                            Kicker = 26,
                            Name = "Power Ball",
                            Num1 = 5,
                            Num2 = 8,
                            Num3 = 19,
                            Num4 = 21,
                            Num5 = 24
                        },
                        new
                        {
                            DrawingId = 86,
                            Date = "1/10/21",
                            Kicker = 10,
                            Name = "Power Ball",
                            Num1 = 14,
                            Num2 = 47,
                            Num3 = 51,
                            Num4 = 56,
                            Num5 = 69
                        },
                        new
                        {
                            DrawingId = 87,
                            Date = "1/10/21",
                            Kicker = 22,
                            Name = "Power Ball",
                            Num1 = 9,
                            Num2 = 20,
                            Num3 = 29,
                            Num4 = 45,
                            Num5 = 47
                        },
                        new
                        {
                            DrawingId = 88,
                            Date = "1/10/21",
                            Kicker = 24,
                            Name = "Power Ball",
                            Num1 = 1,
                            Num2 = 8,
                            Num3 = 44,
                            Num4 = 53,
                            Num5 = 67
                        },
                        new
                        {
                            DrawingId = 89,
                            Date = "1/10/21",
                            Kicker = 9,
                            Name = "Power Ball",
                            Num1 = 4,
                            Num2 = 20,
                            Num3 = 31,
                            Num4 = 33,
                            Num5 = 53
                        },
                        new
                        {
                            DrawingId = 90,
                            Date = "1/10/21",
                            Kicker = 21,
                            Name = "Power Ball",
                            Num1 = 10,
                            Num2 = 24,
                            Num3 = 26,
                            Num4 = 51,
                            Num5 = 68
                        },
                        new
                        {
                            DrawingId = 91,
                            Date = "1/10/21",
                            Kicker = 9,
                            Name = "Power Ball",
                            Num1 = 16,
                            Num2 = 30,
                            Num3 = 35,
                            Num4 = 39,
                            Num5 = 58
                        },
                        new
                        {
                            DrawingId = 92,
                            Date = "1/10/21",
                            Kicker = 4,
                            Name = "Power Ball",
                            Num1 = 1,
                            Num2 = 5,
                            Num3 = 23,
                            Num4 = 24,
                            Num5 = 62
                        },
                        new
                        {
                            DrawingId = 93,
                            Date = "1/10/21",
                            Kicker = 18,
                            Name = "Power Ball",
                            Num1 = 6,
                            Num2 = 8,
                            Num3 = 22,
                            Num4 = 39,
                            Num5 = 40
                        },
                        new
                        {
                            DrawingId = 94,
                            Date = "1/10/21",
                            Kicker = 4,
                            Name = "Power Ball",
                            Num1 = 7,
                            Num2 = 19,
                            Num3 = 23,
                            Num4 = 54,
                            Num5 = 60
                        },
                        new
                        {
                            DrawingId = 95,
                            Date = "1/10/21",
                            Kicker = 26,
                            Name = "Power Ball",
                            Num1 = 5,
                            Num2 = 39,
                            Num3 = 53,
                            Num4 = 54,
                            Num5 = 63
                        },
                        new
                        {
                            DrawingId = 96,
                            Date = "1/10/21",
                            Kicker = 2,
                            Name = "Power Ball",
                            Num1 = 7,
                            Num2 = 20,
                            Num3 = 40,
                            Num4 = 45,
                            Num5 = 69
                        },
                        new
                        {
                            DrawingId = 97,
                            Date = "1/10/21",
                            Kicker = 23,
                            Name = "Power Ball",
                            Num1 = 13,
                            Num2 = 16,
                            Num3 = 20,
                            Num4 = 35,
                            Num5 = 50
                        },
                        new
                        {
                            DrawingId = 98,
                            Date = "1/10/21",
                            Kicker = 9,
                            Name = "Power Ball",
                            Num1 = 19,
                            Num2 = 23,
                            Num3 = 39,
                            Num4 = 59,
                            Num5 = 68
                        },
                        new
                        {
                            DrawingId = 99,
                            Date = "1/10/21",
                            Kicker = 26,
                            Name = "Power Ball",
                            Num1 = 2,
                            Num2 = 7,
                            Num3 = 15,
                            Num4 = 37,
                            Num5 = 57
                        },
                        new
                        {
                            DrawingId = 100,
                            Date = "1/10/21",
                            Kicker = 23,
                            Name = "Power Ball",
                            Num1 = 2,
                            Num2 = 34,
                            Num3 = 37,
                            Num4 = 46,
                            Num5 = 65
                        },
                        new
                        {
                            DrawingId = 101,
                            Date = "1/10/21",
                            Kicker = 19,
                            Name = "Power Ball",
                            Num1 = 18,
                            Num2 = 27,
                            Num3 = 32,
                            Num4 = 39,
                            Num5 = 67
                        },
                        new
                        {
                            DrawingId = 102,
                            Date = "1/10/21",
                            Kicker = 4,
                            Name = "Power Ball",
                            Num1 = 15,
                            Num2 = 40,
                            Num3 = 45,
                            Num4 = 57,
                            Num5 = 64
                        },
                        new
                        {
                            DrawingId = 103,
                            Date = "1/10/21",
                            Kicker = 22,
                            Name = "Power Ball",
                            Num1 = 12,
                            Num2 = 15,
                            Num3 = 34,
                            Num4 = 37,
                            Num5 = 49
                        },
                        new
                        {
                            DrawingId = 104,
                            Date = "1/10/21",
                            Kicker = 9,
                            Name = "Power Ball",
                            Num1 = 8,
                            Num2 = 12,
                            Num3 = 36,
                            Num4 = 46,
                            Num5 = 49
                        },
                        new
                        {
                            DrawingId = 105,
                            Date = "1/10/21",
                            Kicker = 3,
                            Name = "Power Ball",
                            Num1 = 1,
                            Num2 = 24,
                            Num3 = 39,
                            Num4 = 53,
                            Num5 = 54
                        },
                        new
                        {
                            DrawingId = 106,
                            Date = "1/10/21",
                            Kicker = 17,
                            Name = "Power Ball",
                            Num1 = 5,
                            Num2 = 31,
                            Num3 = 33,
                            Num4 = 51,
                            Num5 = 52
                        },
                        new
                        {
                            DrawingId = 107,
                            Date = "1/10/21",
                            Kicker = 19,
                            Name = "Power Ball",
                            Num1 = 26,
                            Num2 = 30,
                            Num3 = 38,
                            Num4 = 57,
                            Num5 = 59
                        },
                        new
                        {
                            DrawingId = 108,
                            Date = "1/10/21",
                            Kicker = 5,
                            Name = "Power Ball",
                            Num1 = 7,
                            Num2 = 17,
                            Num3 = 19,
                            Num4 = 44,
                            Num5 = 67
                        },
                        new
                        {
                            DrawingId = 109,
                            Date = "1/10/21",
                            Kicker = 13,
                            Name = "Power Ball",
                            Num1 = 2,
                            Num2 = 4,
                            Num3 = 10,
                            Num4 = 47,
                            Num5 = 51
                        },
                        new
                        {
                            DrawingId = 110,
                            Date = "1/10/21",
                            Kicker = 14,
                            Name = "Power Ball",
                            Num1 = 8,
                            Num2 = 10,
                            Num3 = 18,
                            Num4 = 33,
                            Num5 = 46
                        },
                        new
                        {
                            DrawingId = 111,
                            Date = "1/10/21",
                            Kicker = 15,
                            Name = "Power Ball",
                            Num1 = 6,
                            Num2 = 22,
                            Num3 = 60,
                            Num4 = 62,
                            Num5 = 66
                        },
                        new
                        {
                            DrawingId = 112,
                            Date = "1/10/21",
                            Kicker = 13,
                            Name = "Power Ball",
                            Num1 = 24,
                            Num2 = 41,
                            Num3 = 47,
                            Num4 = 57,
                            Num5 = 66
                        },
                        new
                        {
                            DrawingId = 113,
                            Date = "1/10/21",
                            Kicker = 26,
                            Name = "Power Ball",
                            Num1 = 24,
                            Num2 = 31,
                            Num3 = 42,
                            Num4 = 52,
                            Num5 = 68
                        },
                        new
                        {
                            DrawingId = 114,
                            Date = "1/10/21",
                            Kicker = 11,
                            Name = "Power Ball",
                            Num1 = 25,
                            Num2 = 36,
                            Num3 = 55,
                            Num4 = 60,
                            Num5 = 61
                        },
                        new
                        {
                            DrawingId = 115,
                            Date = "1/10/21",
                            Kicker = 22,
                            Name = "Power Ball",
                            Num1 = 3,
                            Num2 = 4,
                            Num3 = 22,
                            Num4 = 33,
                            Num5 = 55
                        },
                        new
                        {
                            DrawingId = 116,
                            Date = "1/10/21",
                            Kicker = 14,
                            Name = "Power Ball",
                            Num1 = 10,
                            Num2 = 23,
                            Num3 = 41,
                            Num4 = 53,
                            Num5 = 66
                        },
                        new
                        {
                            DrawingId = 117,
                            Date = "1/10/21",
                            Kicker = 19,
                            Name = "Power Ball",
                            Num1 = 2,
                            Num2 = 43,
                            Num3 = 44,
                            Num4 = 54,
                            Num5 = 58
                        },
                        new
                        {
                            DrawingId = 118,
                            Date = "1/10/21",
                            Kicker = 7,
                            Name = "Power Ball",
                            Num1 = 2,
                            Num2 = 11,
                            Num3 = 45,
                            Num4 = 49,
                            Num5 = 61
                        },
                        new
                        {
                            DrawingId = 119,
                            Date = "1/10/21",
                            Kicker = 20,
                            Name = "Power Ball",
                            Num1 = 8,
                            Num2 = 28,
                            Num3 = 47,
                            Num4 = 50,
                            Num5 = 60
                        },
                        new
                        {
                            DrawingId = 120,
                            Date = "1/10/21",
                            Kicker = 27,
                            Name = "Power Ball",
                            Num1 = 13,
                            Num2 = 27,
                            Num3 = 48,
                            Num4 = 49,
                            Num5 = 64
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
